---
- hosts: localhost
  name: NSX-T Licensing
  gather_facts: false
  vars_files: ../answerfile.yml

  tasks:
    - name: Apply license to NSX-T Manager
      nsxt_licenses:
          hostname: "{{ nsxt_hostname }}.{{ domain }}"
          username: "{{ nsxt_admin_user }}"
          password: "{{ nsxt_password }}"
          validate_certs: "{{ nsxt_validate_certs }}"
          license_key: "{{ nsxt_license }}"
          state: "present"


